name: Build Tag
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: tan14007/clara_frontend/docker_image
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          username: tan14007
          password: ${{ secrets.GITHUB_TOKEN }}
